### ISSUE TITLE
Bug: Popover 컴포넌트에서 border가 발생하는 이슈

### ISSUE THREAD

**Issue by jeongsk** [wanteddev/montage-web#29]
### 요약

사파리 브라우저에서 Popover 컴포넌트를 사용하면 border가 발생하는 이슈가 있습니다.

관련 이슈: https://wantedlab.atlassian.net/browse/PI-64655

### 상세

<img width="603" alt="image" src="https://github.com/wanteddev/wds/assets/57607783/f240192f-dbf8-4a8d-af76-a18caef24ba4">

### 환경

- 패키지 버전: @wanteddev/wds v1.1.2
- 브라우저: 사파리 브라우저

**Comment by Sh031224** [comment]
@jeongsk 이번주 수요일 혹은 다음주 쯤에 다른 작업들과 함께 배포될 예정입니다.

급하게 수정되어야 한다면 `outline-style: none;` 스타일을 주어서 해결할 수 있습니다!
