### ISSUE TITLE
Bug: FlexBox flexGrow, flexShrink not working

### ISSUE THREAD

**Issue by jy-son** [wanteddev/montage-web#44]
### 요약

FlexBox에 flexGrow, flexShrink 스타일 적용이 되지 않고 있습니다.

### 상세

<img width="1006" alt="image" src="https://github.com/wanteddev/wds/assets/89887036/52505d89-6b71-4ead-bd26-196cab06cf9e">

디자인시스템 가이드 문서에서도 해당 prop이 반영되지 않고 있습니다.

### 환경

- `@wanteddev/wds`: 1.1.3
- 제품: 대시보드, 디자인시스템 가이드
- env: dev

**Comment by jy-son** [comment]
```
<FlexBox flexShrink="0" flexGrow="0">
```

숫자가 아닌 문자열로 적용하면 정상동작합니다. 숫자 0을 falsy 값으로 인지하여 적용되지 않는 것으로 보여집니다.

**Comment by Sh031224** [comment]
요건 수정하긴 해야할 것 같아서 재오픈 하겠습니다!

**Comment by jy-son** [comment]
감사합니다 👍
