### ISSUE TITLE
[제안] Tab 배경 색상 제거

### ISSUE THREAD

**Issue by jy-son** [wanteddev/montage-web#6]
**문제가 되고 있는 부분에 대해 설명해주세요.**
- 탭 컴포넌트의 배경색을 변경할 수 없어 [흰색 배경](https://github.com/wanteddev/wds/blob/main/packages/wds/src/components/tab/style.ts#L24) 외에 사용하기에 어려움이 있습니다.

**어떻게 해결되었으면 좋을지 설명해주세요.(설명, 이미지 등)**
- 배경색을 덮어쓸 수 있으면 좋을 것 같아요.
- TabList에 css로 background-color를 넣었을 때 적용되면 좋을 것 같아요.

<img width="1147" alt="image" src="https://github.com/wanteddev/wds/assets/89887036/ca294d12-65ba-4dad-a94f-f2d6f6f834d3">

**추가 설명**
-

**Comment by Sh031224** [comment]
내부 스크롤 영역으로 감싸져있기 때문에
```tsx
<TabList css={{ ['& > div']: { backgroundColor: 'black' } }} />
```
으로 사용 가능합니다.

**Comment by jy-son** [comment]
기본 배경색을 흰색으로 가져가야 하는 이유가 있었을까요?

**Comment by Sh031224** [comment]
> 기본 배경색을 흰색으로 가져가야 하는 이유가 있었을까요?

@jy-son 
mask-image와 함께 그라디언트 주는 부분이 있어서 흰색으로 넣었었는데, 기본값 투명색으로 해도 정상 동작되네요..!
요 부분은 다음 패치때 수정하겠습니다

**Comment by Sh031224** [comment]
[b644b9e](https://github.com/wanteddev/wds/commit/b644b9ea40f531a1559f0a14f20b9f968c807c58)

1.0.0에 반영 예정입니다.

**Comment by jy-son** [comment]
감사합니다 승호님 🙇 🎉
