### ISSUE TITLE
Bug: TextArea disabled not working

### ISSUE THREAD

**Issue by jy-son** [wanteddev/montage-web#9]
### 요약

TextArea에 disabled 속성을 넣었을 때 편집이 됩니다.

### 상세

기본 예제에서 disabled 속성을 넣으면 스타일은 비활성화처럼 보여지는데, 내용은 수정되는 현상입니다.

https://wanteddev.github.io/wds/docs/components/text-area

<img width="752" alt="image" src="https://github.com/wanteddev/wds/assets/89887036/732d68cc-6142-4d3b-88e4-45e5dcade354">

### 환경

- @wanteddev/wds latest

**Comment by Sh031224** [comment]
`disabled` 반영되도록 수정하였고
추가적으로 custom padding 값을 사용하기 편하게 css variable로도 변경했습니다.
